server:
  port: 9500
#注册到Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9200/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
